### ISSUE TITLE
problem on preprocessing crossdock

### ISSUE THREAD

**Issue by BIRD-TAO** [arneschneuing/DiffSBDD#1]
1.
File: ./process_crossdock.py
Line: from analysis.molecule_builder import build_molecule, mol2smiles
Problem: There is no function called mol2smiles in molecule builder
If I simply replace it with Chem.MolToSmiles(), error will occur. 

2. Why does the preprocessing use xyz and atom_types to reconstruct molecules with openable instead of using the sdf file's ground truth?

**Comment by arneschneuing** [comment]
Hi, 

thanks for raising this issue. It seems like we forgot to update process_crossdocked.py. This commit (bbba09eab521ffeceba3af435e2bb46cad8a4d9e) should fix it.

We use openbabel in `compute_smiles()` to infer edges from coordinates because this is what we do for generated molecules as well. In this way, we want to ensure that the same coordinates map to the same SMILES string which we then use for novelty estimation. However, we computed the test set QuickVina scores using the original SDF files.

Best,
Arne
