### ISSUE TITLE
Predicted Ligands are not chemically realistic?!?

### ISSUE THREAD

**Issue by OerthBio-Slav** [arneschneuing/DiffSBDD#16]
I ran the Google Colab notebook for DiffSBDD twice using default parameters with the only difference between the two runs being how I defined the binding pocket. Then I showed the SDF files containing the generated molecules to some colleagues who are chemists and they told me the predicted molecules would not exist in reality. They speculated that the software might only be concerned with placing atoms in 3-dimensional space and ignoring chemical stability when generating molecules. Is there any truth to this? Are there any parameters I can modify to increase the likelihood of the predicted molecules generated being chemically stable/realistic? 
If there is no way to increase the likelihood of generating realistic molecules, it might be helpful to know if any parameters can increase the number of molecules generated

**Comment by arneschneuing** [comment]
Hi @OerthBio-Slav, thanks for your comment.
There are indeed ways to increase the likelihood of generated samples (usually at the expense of diversity) which should lead to more realistic molecules and we are currently working on improving the model.

For the time being, you can generate more molecules by increasing the `n_samples` parameter. You might also want to experiment with different sizes of molecules (using the `ligand_nodes` parameter) because the model often struggles if generated molecules are too big for a given pocket, for example. 
Lastly, you should increase the number of resampling iterations to, say 10, if you use the `inpaint_ca` model. This parameter does not affect the results if you use the default `conditional_full_atom` model, however.
