### ISSUE TITLE
About wandb

### ISSUE THREAD

**Issue by pearl-rabbit** [arneschneuing/DiffSBDD#20]
Hello, I set the parameter mode of wandb to offline, because my machine does not have a network, but it will output "wandb: Network error (TransientException), entering retry loop" when epoch=24.How should I set up to avoid using the network and still use it to record information？
Another question is, why do I sample and analyze when epoch=24?

**Comment by arneschneuing** [comment]
Hi, thanks for your comment. I was not aware that the wandb offline mode is not working. 
Since it only seems to fail during sampling, I assume this is caused by the function that tries to upload a GIF to W&B. For now, you can probably avoid this error by changing the argument in [this line](https://github.com/arneschneuing/DiffSBDD/blob/b5511e55dd4bb3d7e9271e915b2753e822e281a1/lightning_modules.py#L614) and [this line](https://github.com/arneschneuing/DiffSBDD/blob/b5511e55dd4bb3d7e9271e915b2753e822e281a1/lightning_modules.py#L685) to `wandb=None` (similar to [here](https://github.com/arneschneuing/DiffSBDD/blob/b5511e55dd4bb3d7e9271e915b2753e822e281a1/lightning_modules.py#L517)). The animation will then not be accessible from your W&B console but it should still be saved in the log directory.

Regarding your second question, we decided to not evaluate the model at the end of each epoch because sampling a large number of molecules takes some time that we preferred to spend on training the model. If you want to change this behavior, however, you can modify the `eval_epochs`, `visualize_sample_epoch` and `visualize_chain_epoch` parameters. See [here](https://github.com/arneschneuing/DiffSBDD/blob/b5511e55dd4bb3d7e9271e915b2753e822e281a1/configs/crossdocked_ca_cond.yml#L49) for an example.

**Comment by pearl-rabbit** [comment]
Thank you for your answer, it's very helpful for me.
