### ISSUE TITLE
cuda memory usage

### ISSUE THREAD

**Issue by BL-Lac149597870** [arneschneuing/DiffSBDD#7]
Hi @arneschneuing, when training the model with batchsize=1, I get the following error: 
<img width="818" alt="image" src="https://user-images.githubusercontent.com/31134008/202893241-2eb4c411-b283-4d16-bdd8-ca9e08668ad2.png">

It seems there is somethig wrong with the cuda memory (caused by pytorch-lightening?). I don't think the training process would need about 40GB cuda memory with batchsize=1...

**Comment by arneschneuing** [comment]
Hi @BL-Lac149597870,
this can indeed happen if you train a full-atom model with a fully-connected graph because a huge number of edges will be created. Could you please try again with a distance threshold for edges? It can be specified in the config file (in the preprint we use `edge_cutoff: 7.0`).
I hope this will solve the issue.
Best,
Arne

**Comment by BL-Lac149597870** [comment]
Thanks a lot @arneschneuing , that works for me. Thank you very much and really a nice work (I saw the comments from ICLR2023 and I think ICLR reviewers are too harsh) !
